values = {'paludisme': {'mal de tete', 'fievre', 'affaiblissement', 'vomissement', 'toux'},
    'grippe': {'fievre', 'mal de tete', 'fatigue', 'courbatures', 'ecoulement nasal'},
    'rougeole': {'fièvre', 'éruption de bouton rouge', 'rhinite', 'conjonctivite', 'toux'},
    'pneumonie': {'fièvre', 'frissons', 'essoufflement', 'fatigue', 'toux', 'expectoration', 'douleur thoracique'},
 'Acouphene': {'baisse daudition', 'nausee', ' vertiges'},
 'Acetonemie': {'mal de tete', 'vomissement', ' fatigue','agitation'},
 'Adénome de la prostate': {'difficulté à uriner', 'miction', ' fuite urinaire','impossibilité de dormir toute la nuit sans se lever pour uriner'},
 'Allergie alimentaire': {'vomissements', 'diarrhée', ' eczéma','trouble respiratoire','douleur abdominale', 'écoulement nasal', ' chute de la tension artérielle', 'pouls rapide', ' malaise'},
 'Alopécie': {'disparition des cheveux', 'amoindrissement progressif des cheveux'},
 'Amnésie': {'perte de la perte mémoire', 'désorientation dans le temps'},
 'Amygdalite': {'mal de gorge', 'sensation de gêne dans la gorge', 'douleur', 'fièvre', 'mauvaise haleine', 'voix et gorge irritée'},
 'Amenorrhee': {'absence de menstruation', 'bouffée de chaleur', 'mal de tete'},
 'Andropause': {'trouble de sexualite', 'reduction du volume musculaire et perte de force', 'prise de poids', 'sécheresse de la peau', 'perte des cheveux', 'diminution du volume testiculaire'},
 'Angine de poitrine': {'nausée', 'vomissements', 'difficulté respiratoire', 'transpiration importante', 'anxiété', 'malaise'},
 'Angine virale ou bactérienne': {'mal de gorge', 'ganglion au niveau du cou et difficulté à avaler', 'mal de tête', 'fièvre', 'sueurs', 'frissons'},
 'Angiome': {'angiome étendu', 'infection ou saignement', 'apparition brutale dun angiome'},
 'Anorexie': {'perte de poids constante et significative', 'chute des cheveux', 'ongles cassants', 'constipation', 'déséquilibre de la mémoire', 'angoisse'},
 'Anthrax': {'abattement', 'frissons', 'malaise', 'fièvre'},
 'Anurie': {'nausée', 'vomissements', 'mal de tête', 'douleurs lombaires', 'oedèmes', ' hypertension artérielle', 'épilepsie'},
 'Anxiété': {'main droite', 'accélération du pouls', 'palpation', 'difficulté respiratoire', 'sueurs froides', ' tremblements', 'sensation detouffement'},
 'Anemie': {'essoufflement a leffort', 'fatigue anormale', 'palpitations', 'paleur', 'vertiges'},
 'Abcès cutané': {'douleurs', 'peau rouge et chaude', 'gonflement de la peau'},
 'Abcès dentaire': { 'fièvre','fatigue générale', 'mal de tete'},
 'Arthrose': {'gonflement de larticulation', 'limitation des mouvements', 'frottement',  'déformation des articulations atteintes'},
 'Asthme': {'difficulté respiratoire', 'respiration sifflante', 'lèvres pincées',  'essoufflement', 'transpiration excessive',  'toux sèche irritante, parfois chronique' },
'Astigmatisme': {'fatigue oculaire', 'plissement fréquent des yeux', 'mal de tête',  'vertiges', 'éblouissement à la lumière',  'vision double' },
'Autisme': {'insensibilité au bruit', '', 'langage absent',  'difficulté à établir un contact', 'demarche particuliere'},
'Appendicite': {'nausée', 'vomissements', 'perte dappétit',  'fièvre' },
'Ballonnement': {'crampes abdominales', 'diarrhée', 'perte de poids',  'absence complète de gaz et de selles'},
 'Blennorragie': {'inflammation', 'démangeaisons', 'picotement',  'douleur', 'atteinte des yeux',  'envie fréquente duriner'},
'Bouffées de chaleur': {'rougeurs sur le visage', 'sensation de chaleur', 'transpiration importante'},
'Bronchite aiguë': {'fièvre', 'gêne respiratoire', 'douleur',  'fatigue', 'sensation de brûlure dans la poitrine'},
'Bronchite chronique': {'toux', 'expectorations', 'essouflements' },
'Brûlure': {'rougeur de la peau', 'gonflement de la peau', 'douleur'},
'Brûlure destomac': {'sensation de brûlure dans le sternum et la gorge', 'douleur', 'remontées acides',  'goût amer ou acide dans la gorge et la bouche'},
'Bégaiement': {'repetition du meme son', 'hésitations lors de la formulation des phrases', 'utilisation des synonymes',  'trouble moteur'},
'Calcul rénale': {'douleur', 'fièvre', 'frissons',  'nausée', 'brûlure'},
'Cancer de la peau': {'lésions cutanées', 'eczéma', 'lésions rouge',  'macule plane, rosée', 'brûlure'},
'Cancer de la prostate': {'difficulté pour uriner', 'sang dans les urines', 'présence dune métastase osseuse'},
'Cancer du col de lutérus': {'lésions précancéreuse', 'saignement en dehors des regles', 'douleur lombaire'},
'Cancer du foie': {'douleur abdominale', 'amaigrissement', 'fievre','peritonite' },
'Cancer du pancréas': {'douleur abdominale', 'diabète', 'perte de poids','jaunisse', 'augmentation du volume de la rate' },
'Cancer du poumon': {'toux', 'gêne respiratoire', 'infection respiratoire','crachats sanglants', 'douleur' },
'Candidose': {'inflammation du gland', 'perte blanche epaisse', 'démangeaison','inflammation de la vulve', 'douleur' },
'Carence en vitamine C': {'asthénie', 'infection respiratoire', 'douleur articulaire','retard de cicatrisation des plaies' },
'Carie': {'apparition dune tache noire', 'douleur', 'présence dune cavité','mauvaise haleine', 'gonflement de la gencive' },
'Cataracte': {'vision floue', 'gêne à la lumière', 'pupille blanche','vision double', 'altération de la vision des couleurs' },
'Cauchemar': {'rêve effrayant', 'sensation de terreur', 'réveil nocturne lié à la peur ou langoisse','transpiration abondante' },
'Cellulite': {'présence dune peau à laspect granuleux sur les fesses', 'impression de lourdeur au niveau des zones cellulitiques', 'sensibilité à la pression des parties atteintes' },
'Cirrhose': {'démangeaison', 'jaunisse', 'saignement digestifs','présence de liquide dans la cavité abdominale', 'visibilité anormale' },
'Claquage musculaire': {'douleur', 'craquement', 'difficultés à marcher','ecchymose', 'gonflement'},
'Colique du nourrisson': {'agitation inexpliquée', 'pleurs, cris intenses et prolongés', 'ventre dur','ballonnements', 'bruits intestinaux' },
'Colique hépatique': {'douleur', 'gêne respiratoire', 'nausée','vomissements'},
'Colique néphrétique': {'douleur abdominale', 'nausée', 'vomissement','sang dans les urines', 'frissons', 'fièvre', 'brûlure urinaire' },
'Colite': {'diarrhée', 'constipation', 'ballonnement','douleur', 'fatigue', 'fièvre', 'anemie' },
'Conjonctivite': {'sensation de frottement ou de brûlure dans loeil', 'rougeur dans loeil', 'larmoiement','démangeaison', 'sensibilité à la lumière', 'vision trouble', 'douleur' },
'Constipation': {'douleur dans le bas ventre', 'absence des selles de plusieurs jours', 'effort important lors de la poussée','ballonnement', 'hémorroïdes'},
'Coqueluche': {'toux', 'nez qui coule', 'éternuement','fièvre légère' },
'Coup de chaleur': {'sensation de soif intense', 'vertige', 'transpiration','fièvre', 'somnolence', 'mal de tête', 'vision floue' },
'Coronavirus': {'fievre', 'mal de tete', 'fatigue','irritation de la gorge', 'essoufflement', 'nausee', 'diarhee' },
'Dartre': {'présence des plaques de quelques centimètres'},
'Courbature': {'sensation de rigidité musculaire', 'difficulté à se déplacer', 'diminution de la force musculaire','sensation de chaleur dans les parties touchées par les courbatures' },
'Endométriose': {'fatigue', 'douleur au bas ventre', 'difficulté à devenir enceinte','sang dans les urines', 'sang dans les selles' },
'Fibrome': {'douleur au ventre', 'envie fréquente duriner', 'gonflement du bas ventre','infertilité', 'constipation', 'trouble pendant laccouchement'},
'Fibrose pulmonaire': {'difficulté respiratoire', 'toux', 'fatigue','perte de poids', 'perte dappétit', 'gonflement du bout des doigts'},
'Fièvre jaune': {'état fébrile', 'mal de tête', 'douleur musculaire','perte dappétit', 'nausée et', 'vomissement' },
'Fièvre typhoïde': {'fièvre', 'mal de tête', 'douleur musculaire','mal destomac', 'perte dappétit', 'constipation', 'apparition de bouton sur le corps' },
'Gale': {'demangeaison', 'lesion cutanee', 'prurit diffus' },
'Gastro-entérite': {'sang dans les selles', 'vomissement', 'incapacité duriner','douleur abdominale', 'vomissement', 'fièvre', 'respiration rapide' },
'Glossite': {'difficulté pour marcher', 'difficulté pour avaler', 'douleur au niveau de la langue','changement de couleur de la langue', 'gonflement de la langue' },
'Gonorrhée': {'Écoulement purulent et jaune verdâtre par lurètre', 'douleur', 'difficulté à uriner','sensation de brûlure intense en urinant', 'picotement',  'saignement vaginal anormal', 'diarrhée'},
'Goutte': {'douleur au niveau des articulations', 'enflure et rougeur de la région atteinte', 'grande sensation de froid'},
'Grippe': {'fièvre', 'accélération du rythme cardiaque', 'fatigue','perte dappétit', 'nez qui coule',  'mal de gorge', 'difficulté à avaler',  'toux',  'mal de tête'},
'Grippe aviaire': {'fièvre', 'courbature', 'douleur musculaire','conjonctivite bénigne', 'nez qui coule',  'diarrhée', 'difficulté respiratoire',  'toux',  'mal de tête',  'douleur abdominale'},
'Grossesse extra-uterine': {'saignement vaginal leger', 'crampe abdominale', 'chute de tension',  'douleur abdominale'},
'Mauvaise haleine': {'odeur'},
'Hématophobie': {'anxiété', 'malaise vagal', 'Baisse du rythme cardiaque','mal de ventre', 'nausée',  'vertige', 'vomissements',  'tremblement',  'pâleur'},
'Hemoroide': {'sensation de brûlure', 'démangeaison', 'douleur','saignement', 'suintement de mucus par lanus'}
}


def create_test_data():
    return values